# Docker Compose configuration for testing environment
# This extends the main docker-compose.yml with test-specific services and configurations

# Enable BuildKit for optimized builds
x-buildkit: &buildkit
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

# Test environment variables
x-test-env: &test-env
  NODE_ENV: test
  NEXT_PUBLIC_API_URL: http://backend-test:8080
  CI: true

# Test database configuration
x-test-db-env: &test-db-env
  COUCHDB_USER: test_admin
  COUCHDB_PASSWORD: test_password

services:
  # Test CouchDB Database
  couchdb-test:
    image: couchdb:3.3
    container_name: saas-couchdb-test
    environment:
      <<: *test-db-env
    ports:
      - "5985:5984"
    networks:
      - saas-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    tmpfs:
      - /opt/couchdb/data:noexec,nosuid,size=100m

  # Test Backend API
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        <<: *buildkit
        BUILDKIT_INLINE_CACHE: 1
      target: development
    container_name: saas-backend-test
    environment:
      - COUCHDB_URL=http://couchdb-test:5984
      - COUCHDB_USER=test_admin
      - COUCHDB_PASSWORD=test_password
      - JWT_SECRET=test-jwt-secret-key
      - PORT=8080
      - METRICS_PORT=8081
      - LOG_LEVEL=ERROR
      - APP_VERSION=test
    ports:
      - "8082:8080"
      - "9092:9090"
      - "8083:8081"
    depends_on:
      couchdb-test:
        condition: service_healthy
    networks:
      - saas-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  # Website Unit Tests
  website-test:
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile.test
      args:
        <<: *buildkit
        BUILDKIT_INLINE_CACHE: 1
    container_name: saas-website-test
    environment:
      <<: *test-env
    networks:
      - saas-test-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/website/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/shared/node_modules
      - pnpm_test_cache:/root/.local/share/pnpm/store
      - test_coverage:/app/coverage
    command: ["pnpm", "--filter", "@saas-platform/website", "test:docker"]

  # CMS Unit Tests
  cms-test:
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile.test
      args:
        <<: *buildkit
        BUILDKIT_INLINE_CACHE: 1
    container_name: saas-cms-test
    environment:
      <<: *test-env
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: test-nextauth-secret
    networks:
      - saas-test-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/cms/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/shared/node_modules
      - pnpm_test_cache:/root/.local/share/pnpm/store
      - test_coverage:/app/coverage
    command: ["pnpm", "--filter", "@saas-platform/cms", "test:docker"]

  # Integration Test Runner
  integration-test:
    build:
      context: .
      dockerfile: ./Dockerfile.integration-test
      args:
        <<: *buildkit
        BUILDKIT_INLINE_CACHE: 1
    container_name: saas-integration-test
    environment:
      <<: *test-env
      BACKEND_URL: http://backend-test:8080
      WEBSITE_URL: http://website-test:3000
      CMS_URL: http://cms-test:3000
      COUCHDB_URL: http://couchdb-test:5984
      COUCHDB_USER: test_admin
      COUCHDB_PASSWORD: test_password
    depends_on:
      backend-test:
        condition: service_healthy
      couchdb-test:
        condition: service_healthy
    networks:
      - saas-test-network
    volumes:
      - .:/app
      - /app/node_modules
      - test_results:/app/test-results
    command: ["pnpm", "test:integration"]

  # E2E Test Runner with Playwright
  e2e-test:
    build:
      context: .
      dockerfile: ./Dockerfile.e2e-test
      args:
        <<: *buildkit
        BUILDKIT_INLINE_CACHE: 1
    container_name: saas-e2e-test
    environment:
      <<: *test-env
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
      WEBSITE_URL: http://localhost:3000
      CMS_URL: http://localhost:3001
    depends_on:
      backend-test:
        condition: service_healthy
    networks:
      - saas-test-network
    volumes:
      - .:/app
      - /app/node_modules
      - playwright_cache:/ms-playwright
      - test_results:/app/test-results
    command: ["pnpm", "test:e2e", "--reporter=html"]

volumes:
  couchdb_test_data:
    driver: local
  pnpm_test_cache:
    driver: local
  test_coverage:
    driver: local
  test_results:
    driver: local
  playwright_cache:
    driver: local

networks:
  saas-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16