// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogPost struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Excerpt     *string            `json:"excerpt"`
	Content     string             `json:"content"`
	Status      string             `json:"status"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SearchTsv   interface{}        `json:"search_tsv"`
}

type BlogPostCategory struct {
	PostID     pgtype.UUID `json:"post_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type BlogPostTag struct {
	PostID pgtype.UUID `json:"post_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ContactSubmission struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      *string            `json:"name"`
	Subject   *string            `json:"subject"`
	Message   string             `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	SearchTsv interface{}        `json:"search_tsv"`
}

type Medium struct {
	ID         pgtype.UUID        `json:"id"`
	Filename   string             `json:"filename"`
	Path       string             `json:"path"`
	MimeType   string             `json:"mime_type"`
	SizeBytes  int64              `json:"size_bytes"`
	UploaderID pgtype.UUID        `json:"uploader_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Page struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Status      string             `json:"status"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SearchTsv   interface{}        `json:"search_tsv"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         *string            `json:"name"`
	PasswordHash *string            `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
